Repository PrimerEmpleoIT/PEIT-react4-store-app, pull requests merged in 2022-11, with the labels that each got.

#35 Peit 41 crear estado cart
  src/App.jsx
  src/Store/features/Cart/index.js
  src/Store/features/Products/index.js
  src/Store/index.js
Labels: enhancement, good first issue

#37 Peit 42 crud cart
  src/Components/Layout/Navbar/NavBarMobileScreen.jsx
  src/Components/Layout/Navbar/Navbar.jsx
  src/Components/ShoppingCart/DropDown.jsx
  src/Store/features/Cart/index.js
  src/Theme/theme.js
  src/Utils/ProductCard.jsx
  src/assets/Cart/Group 106.svg
Labels: enhancement, good first issue

#38 Peit 28 conect to api
  src/Components/Categories/Categories.jsx
  src/Store/features/Products/index.js
  src/Store/index.js
Labels: enhancement, good first issue

#40 Fix/lighthouse recommendations
  src/Components/Banner/Banner.jsx
  src/Components/Banner/ImageSlider.jsx
  src/Components/Categories/Categories.jsx
  src/Components/Categories/Category.jsx
  src/Components/Categories/CategoryCarousel.jsx
  src/Components/Layout/Layout.jsx
  src/Helpers/storeProducts.js
  src/Utils/ProductCard.jsx
Labels: duplicate, enhancement

#41 Fix button add to cart
  src/Utils/ProductCard.jsx
Labels: enhancement

#42 Hot fix delete comprar button
  src/Utils/ProductCard.jsx
Labels: bug

#43 Fix cart badge styles
  src/Components/ShoppingCart/DropDown.jsx
  src/Store/features/Cart/index.js
  src/Theme/theme.js
Labels: bug

#44 delete unnecesary comments
  src/Store/features/Cart/index.js
Labels: bug

#45 perf: update style for categories components
  src/Components/Ads/Ads.jsx
  src/Components/Categories/Categories.jsx
  src/Components/Categories/Category.jsx
  src/Components/Categories/CategoryCarousel.jsx
  src/Components/Layout/Header/Header.jsx
  src/Components/NewProducts/NewProducts.jsx
  src/Components/ShoppingCart/DropDown.jsx
  src/Utils/ProductCard.jsx
Labels: enhancement
