Repository PrimerEmpleoIT/PEIT-react4-store-app, pull requests merged in 2022-10, with the labels that each got.

#5 FEAT: PEIT-#14 - ChakraUI Theme
  src/Theme/index.js
  src/Theme/theme.js
  src/main.jsx
Labels: enhancement, good first issue

#6 Feat/PEIT-14: Theme ChakraUI
  index.html
  src/Theme/theme.js
Labels: duplicate, enhancement

#8 Peit 01 header
  package-lock.json
  package.json
  src/App.jsx
  src/Components/Layout/Header.jsx
  src/Components/Layout/Header/Header.jsx
  src/Components/Layout/Header/MenuDropDown.jsx
  src/Components/Layout/Header/header.css
  src/Components/Layout/Layout.jsx
  src/Components/Layout/Navbar.jsx
  src/Components/index.js
  src/Theme/theme.js
  src/assets/Header/bx_bx-time.svg
  src/assets/Header/location.svg
  src/assets/navBar/Logo.svg
  src/assets/react.svg
Labels: enhancement, good first issue

#9 Feat/peit 03 banner
  package-lock.json
  package.json
  src/App.jsx
  src/Components/Banner/Banner.jsx
  src/Components/Banner/ImageSlider.jsx
  src/Components/Banner/SlideData.js
  src/assets/Banner/msi1.webp
  src/assets/Banner/msi2.webp
  src/assets/Banner/msi3.webp
  src/assets/Banner/msi4.webp
  src/assets/Banner/msi5.webp
Labels: enhancement, good first issue

#10 Peit 02 nav bar
  package-lock.json
  src/Components/Layout/Layout.jsx
  src/Components/Layout/Navbar.jsx
  src/Components/Navbar/NavBarMobileScreen.jsx
  src/Components/Navbar/Navbar.jsx
  src/Components/index.js
  src/Helpers/index.js
  src/Helpers/navBarLinks.js
  src/assets/navBar/ProfilePhoto.svg
Labels: good first issue

#11 Feat/PEIT-11-Footer
  src/Components/Layout/Footer.jsx
  src/Components/Layout/Footer/AccordionFooter.jsx
  src/Components/Layout/Footer/Footer.jsx
  src/Components/Layout/Layout.jsx
  src/Components/index.js
  src/Helpers/footerList.js
  src/Helpers/index.js
  src/Theme/theme.js
  src/Utils/Utils.jsx
  src/Utils/index.js
  src/assets/Footer/americanExpress.svg
  src/assets/Footer/discover.svg
  src/assets/Footer/masterCard.svg
  src/assets/Footer/paypal.svg
  src/assets/Footer/visa.svg
Labels: enhancement, good first issue

#13 Feat/peit 07 sponsors
  src/App.jsx
  src/Components/Sponsors/Sponsors.jsx
  src/assets/Sponsors/adata.svg
  src/assets/Sponsors/gigabyte.svg
  src/assets/Sponsors/hp.svg
  src/assets/Sponsors/msi.svg
  src/assets/Sponsors/razer.svg
  src/assets/Sponsors/roccat.svg
  src/assets/Sponsors/thermaltake.svg
Labels: enhancement, good first issue

#14 Peit 12 fix nav bar menu mobile
  src/Components/Navbar/NavBarMobileScreen.jsx
Labels: duplicate, enhancement

#12 NewProducts
  package-lock.json
  package.json
  public/Gabinete.jpg
  public/Monitor.jpg
  public/Notebook.jpg
  src/App.jsx
  src/Components/Layout/Layout.jsx
  src/Components/Layout/NewProducts/NewProducts.jsx
  src/Components/Layout/NewProducts/StarRating.jsx
  src/Components/index.js
  src/main.jsx
Labels: enhancement, good first issue

#15 Peit 08 follow us
  package-lock.json
  src/App.jsx
  src/Components/Layout/FollowUs/FollowUs.jsx
  src/Components/index.js
  src/Helpers/followUs.js
  src/assets/FollowUs/hpNotebook.svg
Labels: enhancement, good first issue

#16 PERF/PEIT-19 - ESLint/Prettier
  .eslintrc.cjs
  package-lock.json
  package.json
  src/App.jsx
  src/Components/Banner/Banner.jsx
  src/Components/Banner/ImageSlider.jsx
  src/Components/Banner/SlideData.js
  src/Components/Layout/FollowUs/FollowUs.jsx
  src/Components/Layout/Footer/AccordionFooter.jsx
  src/Components/Layout/Footer/Footer.jsx
  src/Components/Layout/Header/Header.jsx
  src/Components/Layout/Header/MenuDropDown.jsx
  src/Components/Layout/Layout.jsx
  src/Components/Layout/NewProducts/NewProducts.jsx
  src/Components/Layout/NewProducts/StarRating.jsx
  src/Components/Navbar/NavBarMobileScreen.jsx
  src/Components/Navbar/Navbar.jsx
  src/Components/Sponsors/Sponsors.jsx
  src/Components/index.js
  src/Helpers/followUs.js
  src/Helpers/footerList.js
  src/Helpers/index.js
  src/Helpers/navBarLinks.js
  src/Theme/index.js
  src/Theme/theme.js
  src/Utils/index.js
  src/main.jsx
Labels: help wanted, invalid

#17 Feat/PEIT-09 Testimonials
  src/App.jsx
  src/Components/Banner/ImageSlider.jsx
  src/Components/NewProducts/NewProducts.jsx
  src/Components/NewProducts/StarRating.jsx
  src/Components/Testimonials/Testimonials.jsx
  src/Components/Testimonials/carousel.css
  src/Components/index.js
  src/Helpers/index.js
  src/Helpers/testimonials.js
Labels: enhancement, good first issue

#18 feat/PEIT-05 Ads
  src/App.jsx
  src/Components/Ads/Ads.jsx
  src/Components/FollowUs/FollowUs.jsx
  src/Components/Layout/Layout.jsx
  src/Components/index.js
  src/Theme/theme.js
  src/assets/Ads/adsLogo.svg
Labels: enhancement, good first issue

#19 Feat/peit 04 new product
  package-lock.json
  package.json
  src/App.jsx
  src/Components/Banner/Banner.jsx
  src/Components/Banner/ImageSlider.jsx
  src/Components/NewProducts/NewProductSlider.jsx
  src/Components/NewProducts/NewProducts.jsx
  src/Components/index.js
  src/Helpers/NewData.js
  src/Helpers/index.js
Labels: bug, duplicate

#20 Feat/peit 10 benefits
  package-lock.json
  src/App.jsx
  src/Components/Benefits/Benefits.jsx
  src/Components/FollowUs/FollowUs.jsx
  src/Components/index.js
  src/Helpers/Benefits.js
  src/assets/Benefits/Account.svg
  src/assets/Benefits/Saving.svg
  src/assets/Benefits/Support.svg
Labels: enhancement, good first issue

#21 FIX/peit 04 new product
  src/Components/NewProducts/NewProductSlider.jsx
  src/Components/NewProducts/NewProducts.jsx
  src/main.jsx
Labels: bug, duplicate, help wanted

#22 Peit 27 store de estados app
  package-lock.json
  package.json
  src/App.jsx
  src/Helpers/storeProducts.js
  src/Store/features/Products/index.js
  src/Store/index.js
Labels: enhancement, good first issue

#23 Feat/peit 04 new product
  package-lock.json
  package.json
  src/App.jsx
  src/Components/Layout/Layout.jsx
  src/Components/Navbar/Navbar.jsx
  src/Components/NewProducts/NewProductSlider.jsx
  src/Components/NewProducts/NewProducts.css
  src/Components/NewProducts/NewProducts.jsx
  src/Components/NewProducts/StarRating.jsx
  src/Components/index.js
  src/Helpers/pagesRoutes.js
  src/Pages/AllOtherProducts.jsx
  src/Pages/DesktopPC.jsx
  src/Pages/Laptops.jsx
  src/Pages/NetworkinDevices.jsx
  src/Pages/OurDeals.jsx
  src/Pages/PcParts.jsx
  src/Pages/PrinterScanners.jsx
  src/Pages/Repairs.jsx
  src/ProyectRoutes.jsx
Labels: enhancement, good first issue

#24 Style/peit 22 home
  package-lock.json
  public/Gabinete.jpg
  public/Monitor.jpg
  public/Notebook.jpg
  src/App.jsx
  src/Components/Banner/Banner.jsx
  src/Components/Banner/ImageSlider.jsx
  src/Components/FollowUs/FollowUs.jsx
  src/Components/Layout/Layout.jsx
  src/Components/Navbar/Navbar.jsx
  src/Components/NewProducts/NewProductSlider.jsx
  src/Components/NewProducts/NewProducts.css
  src/Components/NewProducts/NewProducts.jsx
  src/Components/Testimonials/Testimonials.jsx
  src/Components/index.js
  src/Helpers/NewData.js
  src/Helpers/index.js
  src/Pages/index.js
  src/ProyectRoutes.jsx
  src/Routes/ProyectRoutes.jsx
  src/Routes/index.js
  src/Services/customHook.js
  src/Services/index.js
  src/assets/NewProducts/Gabinete.webp
  src/assets/NewProducts/Monitor.webp
  src/assets/NewProducts/Notebook.webp
  src/main.jsx
Labels: duplicate, enhancement

#26 Feat/peit 04 new product
  package-lock.json
  package.json
  src/App.jsx
  src/Components/Layout/Layout.jsx
  src/Components/Layout/Navbar/Navbar.jsx
  src/Components/NewProducts/NewProducts.jsx
  src/Components/index.js
  src/Helpers/NewData.js
  src/Helpers/navBarLinks.js
  src/Helpers/pagesRoutes.js
  src/Pages/HomeRoute.jsx
  src/Pages/NetworkinDevices.jsx
  src/Pages/NetworkingDevices.jsx
  src/Pages/index.js
  src/Routes/ProyectRoutes.jsx
  src/Routes/index.js
Labels: bug

#27 STYLES/PEIT-24 Agregar variables del theme a los componentes
  index.html
  public/logo-tech.svg
  public/vite.svg
  src/App.jsx
  src/Components/Banner/Banner.jsx
  src/Components/Banner/ImageSlider.jsx
  src/Components/Banner/SlideData.js
  src/Components/Benefits/Benefits.jsx
  src/Components/FollowUs/FollowUs.jsx
  src/Components/Layout/Benefits/Benefits.jsx
  src/Components/Layout/Layout.jsx
  src/Components/Layout/Navbar/NavBarMobileScreen.jsx
  src/Components/Layout/Navbar/Navbar.jsx
  src/Components/NewProducts/NewProducts.jsx
  src/Components/NewProducts/StarRating.jsx
  src/Components/index.js
  src/Helpers/SlideData.js
  src/Helpers/followUs.js
  src/Helpers/index.js
  src/Pages/HomeRoute.jsx
  src/Pages/NetworkingDevices.jsx
  src/Pages/index.js
Labels: bug, duplicate, help wanted, invalid

#28 FEAT/PEIT-26 Product Card
  src/Components/NewProducts/NewProducts.jsx
  src/Components/index.js
  src/Helpers/NewData.js
  src/Helpers/index.js
  src/Helpers/products.js
  src/Utils/ProductCard.jsx
  src/Utils/StarRating.jsx
  src/Utils/index.js
Labels: enhancement, good first issue

#29 Feat peit 06 categories
  src/App.jsx
  src/Components/Categories/Categorie.jsx
  src/Components/Categories/Categories.jsx
  src/Components/index.js
  src/Helpers/storeProducts.js
  src/Pages/HomeRoute.jsx
  src/Store/features/Products/index.js
Labels: enhancement

#30 FEAT/PEIT-30 Category Carousel
  .prettierrc.json
  package-lock.json
  package.json
  src/Components/Categories/Categorie.jsx
  src/Components/Categories/Categories.jsx
  src/Components/Categories/Category.jsx
  src/Components/Categories/CategoryCarousel.jsx
  src/Components/NewProducts/NewProducts.jsx
  src/Components/index.js
  src/Helpers/NewData.js
  src/Helpers/storeProducts.js
  src/Pages/HomeRoute.jsx
  src/Utils/ProductCard.jsx
  src/assets/Categories/CustomeBuilds.webp
  src/assets/Categories/Desktops.webp
  src/assets/Categories/GamingMonitor.webp
  src/assets/Categories/MSILaptops.webp
Labels: enhancement, good first issue

#31 FIX/PEIT-33 Corregir rutas absolutas y tamaño de imágenes
  src/Components/Sponsors/Sponsors.jsx
  src/Helpers/followUs.js
  src/Utils/ProductCard.jsx
  src/assets/Banner/msi1.webp
  src/assets/FollowUs/desktop.webp
  src/assets/FollowUs/desktopW10.webp
  src/assets/FollowUs/hpNotebook.svg
  src/assets/FollowUs/keyboardRGB.webp
  src/assets/FollowUs/laptop.webp
  src/assets/FollowUs/mouse.webp
  src/assets/FollowUs/notebook.webp
  src/assets/FollowUs/setup.webp
  src/assets/FollowUs/setupRGB.webp
  src/assets/FollowUs/threeMonitors.webp
Labels: bug, invalid

#32 Feat spinner button most popular
  src/Components/Categories/Categories.jsx
  src/Components/Categories/Category.jsx
  src/Components/Categories/CategoryCarousel.jsx
Labels: enhancement

#33 hot fix setTimeOut function in categories
  src/Components/Categories/Categories.jsx
Labels: bug

#34 fix: Modify absolute path images
  src/Helpers/SlideData.js
Labels: bug, invalid
